blog/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from main import views
from django.conf.urls.static import static
from django.conf import settings
# from blog.settings import MEDIA_ROOT
# from django.views.static import serve

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls', namespace='account')),
    path('article/', include('article.urls', namespace='article')),
    path('upload_profile/', include('upload_profile.urls', namespace='upload_profile')),
    path('main/', include('main.urls', namespace='main')),
    re_path('.*', views.main),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

upload_profile/urls.py
from django.urls import path
from . import views

app_name = 'upload_profile'
urlpatterns = [
    path('', views.upload_profile, name='upload_profile'),
    path('add/', views.add, name='add'),
    path('detail/', views.detail, name='detail'),

]

upload_profile/models.py
from django.db import models
from django.utils import timezone


# Create your models here.

class Photo(models.Model):
    user_name = models.CharField(max_length=30)
    user_image = models.ImageField(upload_to='image/', blank=False, null=False)
    upload_date = models.DateField(default=timezone.now)
    introduce = models.FileField(upload_to='introduce/')

    def __str__(self):
        return self.user_name

upload_profile/views.py
from django.shortcuts import render

from upload_profile.models import Photo


# Create your views here.
def upload_profile(request):
    """
    Render the main page
    """
    context = {'like': 'Django 很棒'}
    return render(request, 'upload_profile/upload_profile.html', context)


def add(request):
    if request.method == "POST":
        user_name = request.POST.get('user_name')  # 對應剛剛add.html 中的input name
        user_img = request.FILES.get('user_image')
        introduce = request.FILES.get('introduce')
        user = Photo(user_name=user_name, user_image=user_img, introduce=introduce)
        user.save()
    return render(request, 'upload_profile/add.html', locals())


def detail(request):
    list_user = Photo.objects.all()  # 把資料庫中所有的user資料全部撈出來
    return render(request, 'upload_profile/detail.html', locals())

upload_profile/templates/upload_profile/add.html
{% extends 'main/base.html' %}
{% load static %}
{% block heading %}
簽到簿
<button type="button" class="btn btn-primary"><a href="{% url 'upload_profile:add' %}">簽到簿</a></button>
<button type="button" class="btn btn-primary"><a href="{% url 'upload_profile:detail' %}">查看簽到簿</a></button>
{% endblock %}

{% block content %}
    <form action="/upload_profile/add/" enctype="multipart/form-data" method="post">
        {% csrf_token %} <!--防止跨站請求偽造-->
        <br>
        <label for="user_name">名字:</label>
        <input type="text" name="user_name"><br><br>
        <label for="user_image">大頭貼:(.png)</label><br>
        <input type="file" name="user_image"><br><br>
        <label for="introduce">自我介紹:(.txt)</label><br>
        <input type="file" name="introduce"><br><br>
        <input type="submit" value="提交">

    </form>
{% endblock %}

upload_profile/templates/upload_profile/detail.html
{% extends 'main/base.html' %}
{% load static %}
{% block heading %}
所有使用者
<button type="button" class="btn btn-primary"><a href="{% url 'upload_profile:add' %}">簽到簿</a></button>
<button type="button" class="btn btn-primary"><a href="{% url 'upload_profile:detail' %}">查看簽到簿</a></button>
{% endblock %}

{% block content %}

    {% for user in list_user %}
        <h5>{{ user.user_name }}</h5>
        <p><img src="/static{{ user.user_image.url }}" alt=""  width="100" height="150"></p>
        <!--<img src="/static/main/img/bike.jpg" alt=""  width="50" height="60"> -->
        <div>
            {% for line in user.introduce.readlines %}
                <p>{{ line.decode }}</p>
            {% endfor %}

        </div>

    {% endfor %}
{% endblock %}

upload_profile/templates/upload_profile/upload_profile.html
{% extends 'main/base.html' %}
{% load static %}
{% block heading %}
首頁
<button type="button" class="btn btn-primary"><a href="{% url 'upload_profile:add' %}">簽到簿</a></button>
<button type="button" class="btn btn-primary"><a href="{% url 'upload_profile:detail' %}">查看簽到簿</a></button>
{% endblock %}
{% block content %}
    <br>
    <p style="background-color:Orange;">這是主要內容</p>
{% endblock %}