account/urls.py
from django.urls import path
from account import views

app_name = 'account'
urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),

]

article/urls.py
from django.urls import path
from article import views


app_name = 'article'
urlpatterns = [
    path('', views.article, name='article'),
    path('articleCreate/', views.articleCreate, name='articleCreate'),
    path('articleRead/<int:articleId>/', views.articleRead, name='articleRead'),
    path('articleUpdate/<int:articleId>/', views.articleUpdate, name='articleUpdate'),
    path('articleDelete/<int:articleId>/', views.articleDelete, name='articleDelete'),
    path('articleSearch/', views.articleSearch, name='articleSearch'),
    path('articleLike/<int:articleId>/', views.articleLike, name='articleLike'),
    
    path('commentCreate/<int:articleId>/', views.commentCreate, name='commentCreate'),
    path('commentUpdate/<int:commentId>/', views.commentUpdate, name='commentUpdate'),
    path('commentDelete/<int:commentId>/', views.commentDelete, name='commentDelete'),
    
]

blog/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from main import views
from django.conf.urls.static import static
from django.conf import settings
# from blog.settings import MEDIA_ROOT
# from django.views.static import serve

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls', namespace='account')),
    path('article/', include('article.urls', namespace='article')),
    path('upload_profile/', include('upload_profile.urls', namespace='upload_profile')),
    path('main/', include('main.urls', namespace='main')),
    re_path('.*', views.main),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from main import views


app_name = 'main'
urlpatterns = [
    path('', views.main, name='main'),
    path('about/', views.about, name='about'),
    path('bike/', views.bike, name='bike'),
]

upload_profile/urls.py
from django.urls import path
from . import views

app_name = 'upload_profile'
urlpatterns = [
    path('', views.upload_profile, name='upload_profile'),
    path('add/', views.add, name='add'),
    path('detail/', views.detail, name='detail'),

]

main/models.py
from django.db import models

# Create your models here.

main/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.urls.base import reverse


def main(request):
    """
    Render the main page
    """
    context = {'like': 'Django 很棒'}
    return render(request, 'main/main.html', context)


def about(request):
    """
    Render the about page
    """
    return render(request, 'main/about.html')


def bike(request):
    """
    Render the bike page
    """
    return render(request, 'main/bike.html')


def admin_required(func):
    def auth(request, *args, **kwargs):
        if not request.user.is_superuser:
            messages.error(request, '請以管理者身份登入')
            return redirect(reverse('account:login') + '?next=' + request.get_full_path())
        return func(request, *args, **kwargs)

    return auth

main/templates/main/about.html
{% extends 'main/base.html' %}
{% block heading %}關於{% endblock %}
{% block content %}
    <h2>關於 林至丞的部落格</h2>
    <p>歡迎來到林至丞的 部落格,你可以到留言版留言</p>
{% endblock %}

main/templates/main/base.html
<!doctype html>
{% load static %}
<html>
<head>
<title>部落格</title>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet">
<link rel="stylesheet" href="{% static 'main/css/main.css' %}">
{% block css %}{% endblock %}
</head>
<body>
{% include 'main/menu.html' %}
<div class="container-fluid p-2 bg-info text-white text-center">
  <h2>部落格 -- {% block heading %}{% endblock %}</h2>
</div>
{% block content %}{% endblock %}
<div class="container mt-5">
  <div class="row">
    <div class="col-sm-4">
      <h3>第一欄</h3>
<p class="navbar"><h3>{{ like }}{{ time }}</h3>
<p class="applylarge applyred">這是多重 Class 的例子。</p>
<b class="special">同一個選擇器</b>可以<i class="special">有不同的 instance。</i>
    </div>
    <div class="col-sm-4">
      <h3>第二欄</h3>
<p class="navbar"><p>這是用 Class 選擇器的例子。</p>
<p id="footer">這是用 ID 選擇器的例子。</p>
<p>{{ like }}</p>
    </div>
    <div class="col-sm-4">
      <h3>第三欄</h3>
 <p>這是林至丞(Jason)第一次用Django做好的部落格!</p>
 <b class="special">同一個選擇器</b>可以<i class="special">有不同的 instance。</i>
 <div class="large">這是 DIV 範例。</div>
    </div>
  </div>
</div>

{% for message in messages %}
 <p class="{{ message.tags }}">{{ message }}</p>
{% endfor %}
<meta name="viewport" content="width=device-width, initial-scale=1">

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
{% block script %}{% endblock %}
</body>
</html>

main/templates/main/bike.html
{% load static %}
<head>
<title>重機</title>
<meta charset="utf-8">
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
<link rel="stylesheet" href="{% static 'main/css/bike.css' %}">
{% block css %}{% endblock %}
</head>
{% block content %}
{% include 'main/menu.html' %}
    <h2>林至丞的重機</h2>
    <p>歡迎來到林至丞的重機</p>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
{% endblock %}

main/templates/main/main.html
{% extends 'main/base.html' %}
{% load static %}
{% block heading %}
首頁
<h3 class="bg-info p-3">
    <!--<h3 style="background-color:Tomato;">-->
    <button type="button" class="btn btn-primary"><a class="text-primary" href="/">林至丞的 Django Blog!!</a></button>
    <button type="button" class="btn btn-primary"><a class="text-primary" href="{% url 'main:bike' %}">林至丞的重機</a></button>
    <button type="button" class="btn btn-primary"><a class="text-primary" href="{% url 'upload_profile:upload_profile' %}">簽到簿</a></button>
</h3>
{% endblock %}
{% block content %}
<br>
<p style="background-color:Orange;">這是主要內容</p>
{% endblock %}

main/templates/main/menu.html
<ul id="menu">
  <li><button type="button" class="btn btn-primary"><a href="{% url 'main:main' %}">首頁</a></button></li>
  <li><button type="button" class="btn btn-primary"><a href="{% url 'main:about' %}">關於</a></button></li>
  <li><button type="button" class="btn btn-primary"><a href="{% url 'article:article' %}">留言板</a></button></li>
  <li><button type="button" class="btn btn-primary"><a href="http://127.0.0.1:8000/admin/">admin</a></button></li>
  {% if user.is_authenticated %}
    <li><button type="button" class="btn btn-primary"><a href="{% url 'account:logout' %}">登出 ({{ user.username }})</a></button></li>
  {% else %}
    <li><button type="button" class="btn btn-primary"><a href="{% url 'account:register' %}">註冊</a></button></li>
    <li><button type="button" class="btn btn-primary"><a href="{% url 'account:login' %}">登入</a></button></li>
  {% endif %}
</ul>